- name: Launch HTTPD container
  docker_container:
    name: my-http-container
    image: flooer/tp-devops-httpd:v1.0
    ports:
      - "80:80"
    networks:
      - name: app-network
    state: started