- name: Launch Spring Boot container
  docker_container:
    name: backend
    image: flooer/tp-devops-backend:v1.0
    ports:
      - "8080:8080"
    networks:
      - name: app-network
    state: started
