version: '3.9'

services:
  database:
    build: .  # Path to your Postgres Dockerfile
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd  # Database environment variables
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network  # Connect to app-network

  backend:
    build: ./demo  # Path to your Spring Boot Dockerfile
    container_name: my-springboot-container
    depends_on:
      - database  # Wait for database to be ready before starting
    networks:
      - app-network  # Connect to app-network

  httpd:
    build: ./html  # Path to your Apache Dockerfile
    container_name: my-http-container
    ports:
      - "80:80"  # Expose HTTP on port 80
    networks:
      - app-network  # Connect to app-network
    depends_on:
      - backend  # Wait for backend to be ready before starting

networks:
  app-network:
    driver: bridge  # Define the network driver

volumes:
  pgdata:  # Create a named volume to persist database data
