all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /opt/docker_venv/bin/python
  children:
    prod:
      hosts:
        flo.oerlemans.takima.cloud:
