- name: Launch PostgreSQL container
  docker_container:
    name: my-postgres-container
    image: flooer/tp-devops-database:v1.0
    pull: always
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - name: app-network
    state: started
